import { Geist, Geist_Mono , Quicksand , Nunito , } from "next/font/google";
import "./globals.css";
import BootstrapClient from "./component/BootstrapClient";
import 'bootstrap/dist/css/bootstrap.min.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quick = Quicksand({
  variable: "--font-quick-sand",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito-sand",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
         <style>
          {`
              h1, h2, h3, h4, h5, button , a, input , p {
                font-family: ${quick.style.fontFamily};
              }
              body {
                font-family: ${quick.style.fontFamily};
              }
              .controls .btn{
                font-family: ${nunito.style.fontFamily};
              }
            `}
         </style>
        <BootstrapClient />
        {children}
      </body>
    </html>
  );
}
